name: rdata
channels:
  - conda-forge
dependencies:
  - root
  - numpy
  - pandas
  - matplotlib
  - ipympl
  - uproot
  - cmake
  - boost
  - numpy
  - pyyaml
  - icu
  - conda-build
  - conda-verify
  - bc
  - nbgitpuller
  - pip
  - pandas
  - wget
