name: bamboo
channels:
  - conda-forge
dependencies:
  - root=6.22.8
  - cmake
  - boost
  - numpy
  - pyyaml
  - icu
  - conda-build
  - pip
  - pip:
    - pytest
    - nbgitpuller
    - git+https://gitlab.cern.ch/cp3-cms/bamboo.git@f23e1d062a247cbaf366a65c8507508cac08e051
