{% set name = "plotIt" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cp3-llbb/{{ name }}/archive/master.tar.gz
  sha256: e3253c0d17e7d5081a6385b1a8d9472471c616c29edea90f72d19ee7152d894b
  patches:
    - path_test.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - automake
    - root-binaries=6.24.2
  host:
    - boost-cpp
    - root_base=6.24.2
    - root-binaries=6.24.2
  run:
    - boost-cpp
    - root_base=6.24.2

test:
  requires:
    - python
    - pyyaml
    - requests
    - root=6.24.2
    - imagemagick
  source_files:
    - test
  commands:
    - cd test
    - ./run_tests.sh

about:
  home: https://github.com/cp3-llbb/{{ name }}
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Prefer the short version, e.g: GPL-2.0 instead of GNU General Public License version 2.0
  # See https://opensource.org/licenses/alphabetical
  license: GPL-3.0-or-later
  # The license_family, i.e. "BSD" if license is "BSD-3-Clause". (optional)
  license_family: GPL
  # It is strongly encouraged to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # See https://conda.pydata.org/docs/building/meta-yaml.html#license-file
  # license_file: LICENSE.txt
  summary: "A utility to plot ROOT histograms"

  # The remaining entries in this section are optional, but recommended.
  description: |
    plotIt is a simple and fast tool to turn ROOT histograms into stack plots
  doc_url: http://cp3-llbb.github.io/plotit/
  home: https://github.com/cp3-llbb/{{ name }}

extra:
  recipe-maintainers:
    - cp3-llbb
    - swertz
    - pieterdavid
