{% set name = "bamboo" %}
{% set version = "0.1.0beta2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://gitlab.cern.ch/cp3-cms/{{ name }}/-/archive/master/{{ name }}-master.tar.bz2"
  sha256: 25c911654b0f70b69a9111899e757acfb1b395d488fa6d193b62a2f0e91f63e9

build:
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - root-binaries
  host:
    - python
    - pip
    - scikit-build
    - pytest-runner
    - boost
    - root_base
    - root-binaries
    - pytorch
  run:
    - boost
    - root_base
    - root-binaries
    - PyYAML
    - numpy
    - requests

test:
  requires:
    - pytest
    - pytorch
  source_files:
    - tests
    - examples/nanozmumu.py
    - examples/test1.yml
  commands:
    - "pytest tests"

about:
  home: "https://cp3.irmp.ucl.ac.be/~pdavid/bamboo/index.html"
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: "A high-level HEP analysis library for ROOT::RDataFrame"
  doc_url: "https://cp3.irmp.ucl.ac.be/~pdavid/bamboo/index.html"
  dev_url: "https://gitlab.cern.ch/cp3-cms/bamboo"

extra:
  recipe-maintainers:
    - pieterdavid
